# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
# IP: The module: 'system_axi_hp2_interconnect_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/bd_c0fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/bd_c0fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/bd_c0fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/bd_c0fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/bd_c0fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sarn_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_srn_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_m00s2a_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_hp2_interconnect_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.srcs/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/system_axi_hp2_interconnect_0.xci
# IP: The module: 'system_axi_hp2_interconnect_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/bd_c0fd.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_0/bd_c0fd_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_2/bd_c0fd_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_3/bd_c0fd_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_4/bd_c0fd_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_9/bd_c0fd_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_1/bd_c0fd_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_5/bd_c0fd_s00a2s_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_6/bd_c0fd_sarn_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_7/bd_c0fd_srn_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/bd_0/ip/ip_8/bd_c0fd_m00s2a_0_ooc.xdc

# XDC: /home/lc35648/hdl/projects/fmcomms2/zed/fmcomms2_zed.gen/sources_1/bd/system/ip/system_axi_hp2_interconnect_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_hp2_interconnect_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
